# Generated by Django 3.1.3 on 2020-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20201125_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
